name: Run tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9 # this is pinned in dev-environment file
          mamba-version: "*"
          channels: conda-forge
          activate-environment: {{ cookiecutter.project_slug }}-dev
          environment-file: dev-environment.yml
      
      - name: Install matrix python
        shell: bash -l {0}
        {% raw -%}
        run: |
          conda install python=${{ matrix.python-version }}
        {%-endraw %}
        

      - name: Install {{ cookiecutter.package }}
        shell: bash -l {0}
        run: |
          pip install -e .

      - run: mkdir coverage

      - name: Run Tests
        shell: bash -l {0}
        run: |
          pytest --cov-report term --cov={{ cookiecutter.package }} --junitxml=./coverage/pytest.xml | tee ./coverage/pytest-coverage.txt

      - name: store coverage files
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage