# conda env create -f environment.yml
name: lume-services-model-template
channels:
  - conda-forge
dependencies:
  - python=3.9
  - cookiecutter
  - versioneer
  - pytablewriter
  - gitpython
  - jupyterlab
  - tree
  - pip:
    - git+https://github.com/slaclab/lume-model.git  # Until lume-model updated in conda-forge
