name: {{ cookiecutter.project_name }}
channels:
  - conda-forge
dependencies:
  - prefect<2.0 # until lume-services registered with conda
  - lume-model>=1.4 # until lume-services registered with conda
  - pip 
  - pip: 
    - git+https://github.com/jacquelinegarrahan/lume-services.git
